name: e2e-tests

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:
  kubernetes-test:
    env:
      KUBECONFIG: /tmp/kube-config-otelcol-e2e-testing
    strategy:
      matrix:
        k8s-version: ["v1.26.0", "v1.25.3", "v1.24.7", "v1.23.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19   
      - name: Cache Go
        id: go-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }} 
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: make -j2 gomoddownload
      - name: Build Docker Image
        run: |
            make docker-otelcontribcol
      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}
          kubectl_version: ${{ matrix.k8s-version }}
          cluster_name: kind
      - name: Kind load image
        run: |
          kind load docker-image otelcontribcol:latest --name kind
      - name: run e2e tests
        run: |    
          cd processor/k8sattributesprocessor
          go test -v --tags=e2e
